import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F1F5F9" },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  container: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },
  header: { marginBottom: 20 },
  greetingText: { fontSize: 24, fontWeight: "800", color: "#0F172A" },
  dateText: { fontSize: 14, color: "#64748B" },
  statsCard: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 20,
    elevation: 2,
    marginBottom: 20,
  },
  statsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748B",
    textTransform: "uppercase",
    marginBottom: 16,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  statItem: { flex: 1, alignItems: "center" },
  statValue: { fontSize: 28, fontWeight: "800", color: "#0F172A" },
  statLabel: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "600",
    marginTop: 4,
  },
  statDivider: { width: 1, backgroundColor: "#E2E8F0" },
  gajiContainer: {
    backgroundColor: "#F8FAFC",
    padding: 16,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  gajiLabel: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  gajiAmount: { fontSize: 32, fontWeight: "800", color: "#10B981" },
  actionContainer: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 20,
    elevation: 2,
  },
  actionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 16 },
  toggleButton: {
    height: 54,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  toggleOnline: { backgroundColor: "#2563EB" },
  toggleOffline: { backgroundColor: "#94A3B8" },
  toggleText: { color: "#FFF", fontSize: 16, fontWeight: "800" },
  queueHeader: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 12,
    marginTop: 10,
  },
  activeOrderCard: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 20,
    elevation: 3,
    borderWidth: 2,
    borderColor: "#2563EB",
    marginBottom: 16,
  },
  badge: {
    backgroundColor: "#DBEAFE",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 12,
  },
  badgeText: { color: "#1D4ED8", fontSize: 12, fontWeight: "800" },
  orderTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 8,
  },
  orderDetail: { fontSize: 15, color: "#475569", marginBottom: 4 },
  actionBtn: {
    backgroundColor: "#F59E0B",
    height: 54,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },
  btnText: { color: "#FFF", fontSize: 16, fontWeight: "800" },
  inProgressContainer: {
    marginTop: 16,
    borderTopWidth: 1,
    borderColor: "#E2E8F0",
    paddingTop: 16,
  },
  infoText: { color: "#2563EB", fontWeight: "600", marginBottom: 12 },
  label: { fontSize: 13, fontWeight: "600", color: "#334155", marginBottom: 8 },
  input: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    height: 50,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 16,
  },
  finishBtn: {
    backgroundColor: "#10B981",
    height: 54,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  photoBtn: {
    backgroundColor: "#E2E8F0",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  photoBtnSuccess: { backgroundColor: "#D1FAE5", borderColor: "#10B981" },
  photoBtnText: { color: "#0F172A", fontWeight: "700", fontSize: 15 },
  rekapNavButton: {
    marginTop: 24,
    backgroundColor: "#EFF6FF",
    height: 54,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  rekapNavText: { color: "#1D4ED8", fontSize: 16, fontWeight: "700" },
  logoutButton: {
    marginTop: 12,
    backgroundColor: "#FEF2F2",
    height: 54,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  logoutText: { color: "#DC2626", fontSize: 16, fontWeight: "700" },
  backButton: {
    alignSelf: "flex-start",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#E2E8F0",
    borderRadius: 8,
    marginBottom: 16,
  },
  backButtonText: { color: "#334155", fontWeight: "700", fontSize: 14 },
  rekapHeaderTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 16,
  },
  rekapEmpty: {
    fontSize: 15,
    color: "#64748B",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 20,
  },
  rekapCard: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 1,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  rekapCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  rekapDate: { fontSize: 13, color: "#64748B", fontWeight: "600" },
  rekapRitTag: {
    fontSize: 12,
    backgroundColor: "#F1F5F9",
    color: "#475569",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    fontWeight: "700",
  },
  rekapLokasi: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 4,
  },
  rekapTonase: { fontSize: 14, color: "#0F172A", fontWeight: "600" },
  rekapDivider: { height: 1, backgroundColor: "#F1F5F9", marginVertical: 12 },
  rekapEarnContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rekapEarnLabel: { fontSize: 13, color: "#64748B", fontWeight: "500" },
  rekapEarnValue: { fontSize: 16, fontWeight: "800", color: "#10B981" },
});
