import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F1F5F9" },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  keyboardAvoid: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },
  headerContainer: { marginBottom: 20 },
  headerTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
  },
  headerSubtitle: { fontSize: 14, color: "#64748B", fontWeight: "600" },

  tabBar: {
    flexDirection: "row",
    backgroundColor: "#FFF",
    padding: 4,
    marginHorizontal: 20,
    marginBottom: 12,
    marginTop: 10,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
  },
  tabItem: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 8,
  },
  tabActive: { backgroundColor: "#EFF6FF" },
  tabText: { fontWeight: "600", color: "#64748B", fontSize: 14 },
  tabTextActive: { color: "#2563EB", fontWeight: "800" },

  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    elevation: 2,
    marginBottom: 20,
  },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 13, fontWeight: "600", color: "#334155", marginBottom: 8 },

  scanSection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderColor: "#E2E8F0",
  },
  scanButton: {
    backgroundColor: "#F1F5F9",
    borderWidth: 2,
    borderColor: "#94A3B8",
    borderStyle: "dashed",
    borderRadius: 12,
    height: 54,
    justifyContent: "center",
    alignItems: "center",
  },
  scanButtonText: { color: "#475569", fontWeight: "700", fontSize: 15 },
  scanSuccessBox: {
    backgroundColor: "#D1FAE5",
    borderWidth: 1,
    borderColor: "#10B981",
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scanSuccessText: { color: "#065F46", fontWeight: "800", fontSize: 14 },
  scanResetText: {
    color: "#047857",
    fontWeight: "700",
    fontSize: 13,
    textDecorationLine: "underline",
  },

  pickerContainer: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    overflow: "hidden",
  },
  picker: { height: 50, width: "100%" },
  loadingWrapper: { height: 50, justifyContent: "center" },
  textInput: {
    height: 50,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
  },
  textInputFocused: { borderColor: "#3B82F6", backgroundColor: "#FFFFFF" },

  submitButton: {
    backgroundColor: "#2563EB",
    height: 54,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  submitButtonDisabled: { backgroundColor: "#94A3B8" },
  submitButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
  logoutButton: {
    marginTop: 12,
    backgroundColor: "#FEF2F2",
    height: 54,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  logoutText: { color: "#DC2626", fontSize: 15, fontWeight: "700" },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 12,
  },
  activeCard: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 1,
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: "#E2E8F0",
    borderLeftColor: "#F59E0B",
  },
  activeStatus: {
    fontSize: 12,
    fontWeight: "800",
    color: "#D97706",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  driverName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 4,
  },
  orderInfo: { fontSize: 14, color: "#64748B", marginBottom: 2 },

  historyCard: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 1,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  historyDate: { fontSize: 13, color: "#64748B", fontWeight: "600" },
  historyStatus: {
    fontSize: 12,
    backgroundColor: "#D1FAE5",
    color: "#065F46",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    fontWeight: "700",
  },
  historyTonase: {
    fontSize: 15,
    fontWeight: "800",
    color: "#10B981",
    marginTop: 8,
  },

  cameraOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  scanTarget: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: "#10B981",
    borderRadius: 20,
    backgroundColor: "transparent",
    marginBottom: 20,
  },
  cameraText: {
    color: "#FFF",
    fontSize: 15,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 40,
  },
  cancelScanBtn: {
    backgroundColor: "#DC2626",
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 10,
  },
  cancelScanText: { color: "#FFF", fontWeight: "bold", fontSize: 15 },
  emptyText: {
    fontSize: 14,
    color: "#94A3B8",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 10,
  },
});
